#!/bin/bash

set -e

RFCS="rfc7230 rfc7231 rfc7232 rfc7233 rfc7234 rfc7235"

echo "Cleaning up local state..."
for rfc in $RFCS; do
    if [ "$rfc-annotated.txt" -nt "$rfc.diff" ]; then
        echo "$rfc-annotated.txt is newer than patch, refusing to remove it"
    else
        rm $rfc-annotated.txt
    fi
done
rm -rf .orig

echo "done!"
